### ISSUE TITLE
Shuffle the questions

### ISSUE THREAD

**Issue by cherryWood55** [cherryWood55/Quiz-Game#2]
_Make the questions appear in a random order so that the player doesn't win just by sheer memorization!_

**Comment by achoudh5** [comment]
I can take this one

**Comment by achoudh5** [comment]
Raised PR #8

**Comment by cherryWood55** [comment]
Thanks! I'll review it.

**Comment by cherryWood55** [comment]
> 
> 
> Raised PR #8


Thanks for your contribution @achoudh5 . Could you please add short comment lines explaining the changes you made?
--

**Comment by achoudh5** [comment]
Added the comments in the commit file.

**Comment by Otumian-empire** [comment]
@achoudh5 Is there something I could work on

**Comment by achoudh5** [comment]
@Otumian-empire I have my own repo which needs a bit of trim, this issue is resolved. You can work on this repo's other issues or come to my casa :P

**Comment by Otumian-empire** [comment]
cool.. I will pass by when I am free.. Thanks anyway
