### ISSUE TITLE
Display the results in a more detailed manner

### ISSUE THREAD

**Issue by cherryWood55** [cherryWood55/Quiz-Game#3]
_Some enhancement features which are pretty easy and fun to do:_
- After the quiz is over, the user would probably want to see the questions they got right or wrong. 

- Also give the user some extra information and encourage them to learn more about the same topic. 

- Add links to appropriate websites where such info could be found.

**Comment by dvfleet413** [comment]
@cherryWood55 Mind if I work on this one??

**Comment by ErisedKT** [comment]
I could work on this if it's still open.

**Comment by cherryWood55** [comment]
Sure. Go ahead!

**Comment by amitrajitbose** [comment]
If this is still available, I would like to work on this @cherryWood55

**Comment by cherryWood55** [comment]
> 
> 
> If this is still available, I would like to work on this @cherryWood55

Yes, it is available.
