### ISSUE TITLE
Save Questions in external files

### ISSUE THREAD

**Issue by Sidx-sys** [cherryWood55/Quiz-Game#9]
Since you are saving all the questions and answers as list elements in the main python script, this program becomes more difficult to manage as more questions and answers are added to it.
_______________________________________________________________________________________________________
Solution : Save the question-answers pairs as a list of ordered sets in an external file which can be easily modified to add or remove questions without having to change the main script.
External files maybe in the form of .csv, .json or .py .

**Comment by Sidx-sys** [comment]
P.S i would like to implement this

**Comment by cherryWood55** [comment]
Good idea to segregate the questions. You can proceed.

**Comment by amitrajitbose** [comment]
A nice idea would be to use JSON files for the questions and answers.
